In [31]:
%pylab inline
%config InlineBackend.figure_format = 'retina'
from ipywidgets import interact
import scipy.stats as stats
import pandas as pd
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions
tfb = tfp.bijectors
import matplotlib.pyplot as plt

import warnings # the warning spam is pointless and annoying
warnings.simplefilter(action="ignore", category=FutureWarning)

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib

In [9]:
df = pd.read_csv("/Users/kynanami/Documents/Winter 2024/MATH 509/filtered_headlines.csv", header=0)

In [34]:
df = df[["IDLink", "Topic", "Facebook", "GooglePlus", "LinkedIn", "Topic 0", "Topic 1", "Topic 2", "Topic 3"]]
df = df.loc[(df["Facebook"] != -1) | (df["GooglePlus"] != -1) | (df["LinkedIn"] != -1)]


obama = tf.cast(df["Topic 0"], tf.float32)
econ = tf.cast(df["Topic 1"], tf.float32)
pal = tf.cast(df["Topic 2"], tf.float32)
ms = tf.cast(df["Topic 3"], tf.float32)

fb = tf.cast(df["Facebook"], tf.float32)
gp = tf.cast(df["GooglePlus"], tf.float32)
li = tf.cast(df["LinkedIn"], tf.float32)

In [35]:
df

,IDLink,Topic,Facebook,GooglePlus,LinkedIn,Topic 0,Topic 1,Topic 2,Topic 3
680,311.0,microsoft,0,0,0,0.006249,0.006526,0.006227,0.980997
681,252.0,economy,0,0,0,0.006372,0.896285,0.006407,0.090936
682,227.0,economy,0,0,0,0.009429,0.817493,0.097070,0.076009
683,307.0,microsoft,0,0,0,0.005882,0.134196,0.005956,0.853966
684,207.0,economy,1,0,0,0.006660,0.413849,0.006671,0.572819
...,...,...,...,...,...,...,...,...,...
86280,61851.0,economy,-1,3,5,0.018213,0.945057,0.018308,0.018422
86281,61865.0,economy,-1,0,1,0.131143,0.820171,0.024560,0.024126
86282,104793.0,palestine,5,1,0,0.518430,0.444394,0.019046,0.018131
86283,104794.0,palestine,0,0,0,0.125082,0.016564,0.398295,0.460058
86284,61870.0,microsoft,-1,1,0,0.016343,0.016523,0.182003,0.785131