In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
# Load the CSV data into a DataFrame
df = pd.read_csv('/content/gdrive/MyDrive/MATH 509 Project/dataset/Data/News_Final.csv')

# Display the first few rows of the DataFrame to verify it's loaded correctly
print(df.head())

    IDLink                                              Title  \
0  99248.0   Obama Lays Wreath at Arlington National Cemetery
1  10423.0        A Look at the Health of the Chinese Economy
2  18828.0   Nouriel Roubini: Global Economy Not Back to 2008
3  27788.0                          Finland GDP Expands In Q4
4  27789.0  Tourism, govt spending buoys Thai economy in J...

                                            Headline  \
0  Obama Lays Wreath at Arlington National Cemete...
1  Tim Haywood, investment director business-unit...
2  Nouriel Roubini, NYU professor and chairman at...
3  Finland's economy expanded marginally in the t...
4  Tourism and public spending continued to boost...

                                     Source    Topic          PublishDate  \
0                                 USA TODAY    obama  2002-04-02 00:00:00
1                                 Bloomberg  economy  2008-09-20 00:00:00
2                                 Bloomberg  economy  2012-01-28 00:00:00
3                                  RTT News  economy  2015-03-01 00:06:00
4  The Nation - Thailand&#39;s English news  economy  2015-03-01 00:11:00

   SentimentTitle  SentimentHeadline  Facebook  GooglePlus  LinkedIn
0        0.000000          -0.053300        -1          -1        -1
1        0.208333          -0.156386        -1          -1        -1
2       -0.425210           0.139754        -1          -1        -1
3        0.000000           0.026064        -1          -1        -1
4        0.000000           0.141084        -1          -1        -1

In [4]:
#Handel missing data
# Check for missing values in each column
missing_data = df.isnull().sum()

# Print the number of missing values in each column
print(missing_data[missing_data > 0])
df = df.dropna()

Headline     15
Source      279
dtype: int64

####Text Preprocessing: Lemmatize the article headlines to bring words to their base or root form. Additionally, remove stopwords, punctuation, and perform lowercasing to standardize the text data for analysis.

In [23]:
import nltk
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [24]:
#Preprocess the Text Data
def preprocess_text(text):
    # Lowercasing
    text = text.lower()

    # Remove punctuation
    text = re.sub(r'[^\w\s]', ' ', text)

    # Tokenize
    tokens = word_tokenize(text)

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]

    # Lemmatize
    lemmatizer = WordNetLemmatizer()
    lemmatized_text = [lemmatizer.lemmatize(token) for token in filtered_tokens]

    # Stemmer
    stemmer = SnowballStemmer('english')
    stemmed_words = [stemmer.stem(token) for token in lemmatized_text]

    # Re-join tokens into a string
    return ' '.join(stemmed_words)

In [25]:
# Apply the preprocessing function to each headline
df['Processed_Headline'] = df['Headline'].apply(preprocess_text)

# Display the processed headlines
print(df[['Headline', 'Processed_Headline']])

                                                Headline  \
0      Obama Lays Wreath at Arlington National Cemete...
1      Tim Haywood, investment director business-unit...
2      Nouriel Roubini, NYU professor and chairman at...
3      Finland's economy expanded marginally in the t...
4      Tourism and public spending continued to boost...
...                                                  ...
93234  The June employment report is viewed as a cruc...
93235  In addition, establish stimulating economic po...
93236  The Palestinian government spends nearly $140 ...
93237  Palestine Youth Orchestra prepares for first U...
93238  Goldstein, the proprietor of the TG Travel Gro...

                                      Processed_Headline
0      obama lay wreath arlington nation cemeteri pre...
1      tim haywood invest director busi unit head fix...
2      nouriel roubini nyu professor chairman roubini...
3      finland economi expand margin three month end ...
4      tourism public spend continu boost economi jan...
...                                                  ...
93234  june employ report view crucial gaug health ec...
93235  addit establish stimul econom polici budget co...
93236  palestinian govern spend near 140 million annu...
93237  palestin youth orchestra prepar first uk tour ...
93238  goldstein proprietor tg travel group llc custo...

[92945 rows x 2 columns]

####Document-Term Matrix (DTM): Transform the preprocessed headlines into a DTM, which quantifies the headlines by the occurrence of words.

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

In [27]:
dtm = vectorizer.fit_transform(df['Processed_Headline'])

In [28]:
dtm_df = pd.DataFrame(dtm.toarray(), columns=vectorizer.get_feature_names_out())

In [29]:
dtm_df

,00,000,000001,00001,000333,0025,003,0031,005930,00am,...,âtoday,äìhave,échappé,école,éducat,élus,était,été,événement,être
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92940,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92941,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92942,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92943,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92944,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#!pip install scikit-learn matplotlib

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.7.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.25.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (24.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

In [ ]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

In [ ]:
pca = PCA().fit(dtm_df)
cumulative_variance_ratio = pca.explained_variance_ratio_.cumsum()

n_components = len(cumulative_variance_ratio[cumulative_variance_ratio <= 0.95]) + 1

In [ ]:
from sklearn.preprocessing import StandardScaler

# Standardizing the features
scaler = StandardScaler()
dtm_scaled = scaler.fit_transform(dtm_df)

In [ ]:
# Initialize PCA
pca = PCA(n_components=#)

# Fit PCA on the DTM or standardized DTM
dtm_pca = pca.fit_transform(dtm_df)  # or dtm_scaled if you've standardized